# Video parameters
videoFolder: "./test"
videoFilename: "0.mp4"
frameRate: 100
recTimeInSec: 10

# Camera parameters
numCams: 6
cameraSelection: [0,1,2,3,4,5]  # selects which cameras are used and in which order
cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraNames: ["Camera1","Camera2","Camera3","Camera4","Camera5","Camera6"]
cameraMake: "basler"
pixelFormatInput: "rgb24"
pixelFormatOutput: "rgb0"

# Compression parameters
ffmpegLogLevel: "quiet"   # "quiet", "warning", "info"
gpuID: 0                  # -1 = CPU, GPU id for Nvidia multi-GPU, default is 0
gpuMake: "nvidia"         # "nvidia", "amd", "intel"          
codec: "h264"             # "h264", "h265", or user-defined video codec
quality: "21"             # 0-55

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
emulate: False
frameWidth: 1152
frameHeight: 1024